/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiThemesRouteImport } from './routes/api/themes'
import { Route as ApiStocksRouteImport } from './routes/api/stocks'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiRadarRouteImport } from './routes/api/radar'
import { Route as ApiPositionsRouteImport } from './routes/api/positions'
import { Route as ApiMyResearchRouteImport } from './routes/api/my-research'
import { Route as ApiMarketNewsRouteImport } from './routes/api/market-news'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as ApiWatchlistEntityKeyRouteImport } from './routes/api/watchlist/$entityKey'
import { Route as ApiV1ImpactRouteImport } from './routes/api/v1/impact'
import { Route as ApiV1FeaturesRouteImport } from './routes/api/v1/features'
import { Route as ApiV1ConfirmationRouteImport } from './routes/api/v1/confirmation'
import { Route as ApiStocksEntityKeyRouteImport } from './routes/api/stocks/$entityKey'
import { Route as ApiRecordsRecordKeyRouteImport } from './routes/api/records/$recordKey'
import { Route as ApiPositionsEntityKeyRouteImport } from './routes/api/positions/$entityKey'
import { Route as ApiPortfolioDigestRouteImport } from './routes/api/portfolio/digest'
import { Route as ApiMeBootstrapRouteImport } from './routes/api/me/bootstrap'
import { Route as ApiDiscoverStocksRouteImport } from './routes/api/discover/stocks'
import { Route as ApiDashboardTodayRouteImport } from './routes/api/dashboard/today'
import { Route as ApiV1ReportsLatestRouteImport } from './routes/api/v1/reports/latest'
import { Route as ApiV1PersonalFeedRouteImport } from './routes/api/v1/personal/feed'
import { Route as ApiV1CalibrationScorecardRouteImport } from './routes/api/v1/calibration/scorecard'
import { Route as ApiStocksEntityKeyPricesRouteImport } from './routes/api/stocks/$entityKey.prices'
import { Route as ApiEntitiesEntityKeyRelationsRouteImport } from './routes/api/entities/$entityKey/relations'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemesRoute = ApiThemesRouteImport.update({
  id: '/api/themes',
  path: '/api/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksRoute = ApiStocksRouteImport.update({
  id: '/api/stocks',
  path: '/api/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadarRoute = ApiRadarRouteImport.update({
  id: '/api/radar',
  path: '/api/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPositionsRoute = ApiPositionsRouteImport.update({
  id: '/api/positions',
  path: '/api/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyResearchRoute = ApiMyResearchRouteImport.update({
  id: '/api/my-research',
  path: '/api/my-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketNewsRoute = ApiMarketNewsRouteImport.update({
  id: '/api/market-news',
  path: '/api/market-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWatchlistEntityKeyRoute = ApiWatchlistEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiWatchlistRoute,
} as any)
const ApiV1ImpactRoute = ApiV1ImpactRouteImport.update({
  id: '/api/v1/impact',
  path: '/api/v1/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FeaturesRoute = ApiV1FeaturesRouteImport.update({
  id: '/api/v1/features',
  path: '/api/v1/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConfirmationRoute = ApiV1ConfirmationRouteImport.update({
  id: '/api/v1/confirmation',
  path: '/api/v1/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksEntityKeyRoute = ApiStocksEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiStocksRoute,
} as any)
const ApiRecordsRecordKeyRoute = ApiRecordsRecordKeyRouteImport.update({
  id: '/api/records/$recordKey',
  path: '/api/records/$recordKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPositionsEntityKeyRoute = ApiPositionsEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiPositionsRoute,
} as any)
const ApiPortfolioDigestRoute = ApiPortfolioDigestRouteImport.update({
  id: '/api/portfolio/digest',
  path: '/api/portfolio/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBootstrapRoute = ApiMeBootstrapRouteImport.update({
  id: '/api/me/bootstrap',
  path: '/api/me/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverStocksRoute = ApiDiscoverStocksRouteImport.update({
  id: '/api/discover/stocks',
  path: '/api/discover/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardTodayRoute = ApiDashboardTodayRouteImport.update({
  id: '/api/dashboard/today',
  path: '/api/dashboard/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsLatestRoute = ApiV1ReportsLatestRouteImport.update({
  id: '/api/v1/reports/latest',
  path: '/api/v1/reports/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PersonalFeedRoute = ApiV1PersonalFeedRouteImport.update({
  id: '/api/v1/personal/feed',
  path: '/api/v1/personal/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CalibrationScorecardRoute =
  ApiV1CalibrationScorecardRouteImport.update({
    id: '/api/v1/calibration/scorecard',
    path: '/api/v1/calibration/scorecard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStocksEntityKeyPricesRoute =
  ApiStocksEntityKeyPricesRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => ApiStocksEntityKeyRoute,
  } as any)
const ApiEntitiesEntityKeyRelationsRoute =
  ApiEntitiesEntityKeyRelationsRouteImport.update({
    id: '/api/entities/$entityKey/relations',
    path: '/api/entities/$entityKey/relations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/my-research': typeof ApiMyResearchRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/radar': typeof ApiRadarRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/themes': typeof ApiThemesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/records/$recordKey': typeof ApiRecordsRecordKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRouteWithChildren
  '/api/v1/confirmation': typeof ApiV1ConfirmationRoute
  '/api/v1/features': typeof ApiV1FeaturesRoute
  '/api/v1/impact': typeof ApiV1ImpactRoute
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
  '/api/entities/$entityKey/relations': typeof ApiEntitiesEntityKeyRelationsRoute
  '/api/stocks/$entityKey/prices': typeof ApiStocksEntityKeyPricesRoute
  '/api/v1/calibration/scorecard': typeof ApiV1CalibrationScorecardRoute
  '/api/v1/personal/feed': typeof ApiV1PersonalFeedRoute
  '/api/v1/reports/latest': typeof ApiV1ReportsLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/my-research': typeof ApiMyResearchRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/radar': typeof ApiRadarRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/themes': typeof ApiThemesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/records/$recordKey': typeof ApiRecordsRecordKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRouteWithChildren
  '/api/v1/confirmation': typeof ApiV1ConfirmationRoute
  '/api/v1/features': typeof ApiV1FeaturesRoute
  '/api/v1/impact': typeof ApiV1ImpactRoute
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
  '/api/entities/$entityKey/relations': typeof ApiEntitiesEntityKeyRelationsRoute
  '/api/stocks/$entityKey/prices': typeof ApiStocksEntityKeyPricesRoute
  '/api/v1/calibration/scorecard': typeof ApiV1CalibrationScorecardRoute
  '/api/v1/personal/feed': typeof ApiV1PersonalFeedRoute
  '/api/v1/reports/latest': typeof ApiV1ReportsLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/my-research': typeof ApiMyResearchRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/radar': typeof ApiRadarRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/themes': typeof ApiThemesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/records/$recordKey': typeof ApiRecordsRecordKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRouteWithChildren
  '/api/v1/confirmation': typeof ApiV1ConfirmationRoute
  '/api/v1/features': typeof ApiV1FeaturesRoute
  '/api/v1/impact': typeof ApiV1ImpactRoute
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
  '/api/entities/$entityKey/relations': typeof ApiEntitiesEntityKeyRelationsRoute
  '/api/stocks/$entityKey/prices': typeof ApiStocksEntityKeyPricesRoute
  '/api/v1/calibration/scorecard': typeof ApiV1CalibrationScorecardRoute
  '/api/v1/personal/feed': typeof ApiV1PersonalFeedRoute
  '/api/v1/reports/latest': typeof ApiV1ReportsLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/feed'
    | '/api/health'
    | '/api/history'
    | '/api/market-news'
    | '/api/my-research'
    | '/api/positions'
    | '/api/radar'
    | '/api/status'
    | '/api/stocks'
    | '/api/themes'
    | '/api/watchlist'
    | '/api/workspace'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/records/$recordKey'
    | '/api/stocks/$entityKey'
    | '/api/v1/confirmation'
    | '/api/v1/features'
    | '/api/v1/impact'
    | '/api/watchlist/$entityKey'
    | '/api/entities/$entityKey/relations'
    | '/api/stocks/$entityKey/prices'
    | '/api/v1/calibration/scorecard'
    | '/api/v1/personal/feed'
    | '/api/v1/reports/latest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/feed'
    | '/api/health'
    | '/api/history'
    | '/api/market-news'
    | '/api/my-research'
    | '/api/positions'
    | '/api/radar'
    | '/api/status'
    | '/api/stocks'
    | '/api/themes'
    | '/api/watchlist'
    | '/api/workspace'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/records/$recordKey'
    | '/api/stocks/$entityKey'
    | '/api/v1/confirmation'
    | '/api/v1/features'
    | '/api/v1/impact'
    | '/api/watchlist/$entityKey'
    | '/api/entities/$entityKey/relations'
    | '/api/stocks/$entityKey/prices'
    | '/api/v1/calibration/scorecard'
    | '/api/v1/personal/feed'
    | '/api/v1/reports/latest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/workspace'
    | '/api/feed'
    | '/api/health'
    | '/api/history'
    | '/api/market-news'
    | '/api/my-research'
    | '/api/positions'
    | '/api/radar'
    | '/api/status'
    | '/api/stocks'
    | '/api/themes'
    | '/api/watchlist'
    | '/api/workspace'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/records/$recordKey'
    | '/api/stocks/$entityKey'
    | '/api/v1/confirmation'
    | '/api/v1/features'
    | '/api/v1/impact'
    | '/api/watchlist/$entityKey'
    | '/api/entities/$entityKey/relations'
    | '/api/stocks/$entityKey/prices'
    | '/api/v1/calibration/scorecard'
    | '/api/v1/personal/feed'
    | '/api/v1/reports/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiMarketNewsRoute: typeof ApiMarketNewsRoute
  ApiMyResearchRoute: typeof ApiMyResearchRoute
  ApiPositionsRoute: typeof ApiPositionsRouteWithChildren
  ApiRadarRoute: typeof ApiRadarRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiStocksRoute: typeof ApiStocksRouteWithChildren
  ApiThemesRoute: typeof ApiThemesRoute
  ApiWatchlistRoute: typeof ApiWatchlistRouteWithChildren
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiDashboardTodayRoute: typeof ApiDashboardTodayRoute
  ApiDiscoverStocksRoute: typeof ApiDiscoverStocksRoute
  ApiMeBootstrapRoute: typeof ApiMeBootstrapRoute
  ApiPortfolioDigestRoute: typeof ApiPortfolioDigestRoute
  ApiRecordsRecordKeyRoute: typeof ApiRecordsRecordKeyRoute
  ApiV1ConfirmationRoute: typeof ApiV1ConfirmationRoute
  ApiV1FeaturesRoute: typeof ApiV1FeaturesRoute
  ApiV1ImpactRoute: typeof ApiV1ImpactRoute
  ApiEntitiesEntityKeyRelationsRoute: typeof ApiEntitiesEntityKeyRelationsRoute
  ApiV1CalibrationScorecardRoute: typeof ApiV1CalibrationScorecardRoute
  ApiV1PersonalFeedRoute: typeof ApiV1PersonalFeedRoute
  ApiV1ReportsLatestRoute: typeof ApiV1ReportsLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/themes': {
      id: '/api/themes'
      path: '/api/themes'
      fullPath: '/api/themes'
      preLoaderRoute: typeof ApiThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks': {
      id: '/api/stocks'
      path: '/api/stocks'
      fullPath: '/api/stocks'
      preLoaderRoute: typeof ApiStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radar': {
      id: '/api/radar'
      path: '/api/radar'
      fullPath: '/api/radar'
      preLoaderRoute: typeof ApiRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/positions': {
      id: '/api/positions'
      path: '/api/positions'
      fullPath: '/api/positions'
      preLoaderRoute: typeof ApiPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-research': {
      id: '/api/my-research'
      path: '/api/my-research'
      fullPath: '/api/my-research'
      preLoaderRoute: typeof ApiMyResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-news': {
      id: '/api/market-news'
      path: '/api/market-news'
      fullPath: '/api/market-news'
      preLoaderRoute: typeof ApiMarketNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/watchlist/$entityKey': {
      id: '/api/watchlist/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/watchlist/$entityKey'
      preLoaderRoute: typeof ApiWatchlistEntityKeyRouteImport
      parentRoute: typeof ApiWatchlistRoute
    }
    '/api/v1/impact': {
      id: '/api/v1/impact'
      path: '/api/v1/impact'
      fullPath: '/api/v1/impact'
      preLoaderRoute: typeof ApiV1ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/features': {
      id: '/api/v1/features'
      path: '/api/v1/features'
      fullPath: '/api/v1/features'
      preLoaderRoute: typeof ApiV1FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/confirmation': {
      id: '/api/v1/confirmation'
      path: '/api/v1/confirmation'
      fullPath: '/api/v1/confirmation'
      preLoaderRoute: typeof ApiV1ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks/$entityKey': {
      id: '/api/stocks/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/stocks/$entityKey'
      preLoaderRoute: typeof ApiStocksEntityKeyRouteImport
      parentRoute: typeof ApiStocksRoute
    }
    '/api/records/$recordKey': {
      id: '/api/records/$recordKey'
      path: '/api/records/$recordKey'
      fullPath: '/api/records/$recordKey'
      preLoaderRoute: typeof ApiRecordsRecordKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/positions/$entityKey': {
      id: '/api/positions/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/positions/$entityKey'
      preLoaderRoute: typeof ApiPositionsEntityKeyRouteImport
      parentRoute: typeof ApiPositionsRoute
    }
    '/api/portfolio/digest': {
      id: '/api/portfolio/digest'
      path: '/api/portfolio/digest'
      fullPath: '/api/portfolio/digest'
      preLoaderRoute: typeof ApiPortfolioDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/bootstrap': {
      id: '/api/me/bootstrap'
      path: '/api/me/bootstrap'
      fullPath: '/api/me/bootstrap'
      preLoaderRoute: typeof ApiMeBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover/stocks': {
      id: '/api/discover/stocks'
      path: '/api/discover/stocks'
      fullPath: '/api/discover/stocks'
      preLoaderRoute: typeof ApiDiscoverStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/today': {
      id: '/api/dashboard/today'
      path: '/api/dashboard/today'
      fullPath: '/api/dashboard/today'
      preLoaderRoute: typeof ApiDashboardTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/latest': {
      id: '/api/v1/reports/latest'
      path: '/api/v1/reports/latest'
      fullPath: '/api/v1/reports/latest'
      preLoaderRoute: typeof ApiV1ReportsLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/personal/feed': {
      id: '/api/v1/personal/feed'
      path: '/api/v1/personal/feed'
      fullPath: '/api/v1/personal/feed'
      preLoaderRoute: typeof ApiV1PersonalFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calibration/scorecard': {
      id: '/api/v1/calibration/scorecard'
      path: '/api/v1/calibration/scorecard'
      fullPath: '/api/v1/calibration/scorecard'
      preLoaderRoute: typeof ApiV1CalibrationScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks/$entityKey/prices': {
      id: '/api/stocks/$entityKey/prices'
      path: '/prices'
      fullPath: '/api/stocks/$entityKey/prices'
      preLoaderRoute: typeof ApiStocksEntityKeyPricesRouteImport
      parentRoute: typeof ApiStocksEntityKeyRoute
    }
    '/api/entities/$entityKey/relations': {
      id: '/api/entities/$entityKey/relations'
      path: '/api/entities/$entityKey/relations'
      fullPath: '/api/entities/$entityKey/relations'
      preLoaderRoute: typeof ApiEntitiesEntityKeyRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPositionsRouteChildren {
  ApiPositionsEntityKeyRoute: typeof ApiPositionsEntityKeyRoute
}

const ApiPositionsRouteChildren: ApiPositionsRouteChildren = {
  ApiPositionsEntityKeyRoute: ApiPositionsEntityKeyRoute,
}

const ApiPositionsRouteWithChildren = ApiPositionsRoute._addFileChildren(
  ApiPositionsRouteChildren,
)

interface ApiStocksEntityKeyRouteChildren {
  ApiStocksEntityKeyPricesRoute: typeof ApiStocksEntityKeyPricesRoute
}

const ApiStocksEntityKeyRouteChildren: ApiStocksEntityKeyRouteChildren = {
  ApiStocksEntityKeyPricesRoute: ApiStocksEntityKeyPricesRoute,
}

const ApiStocksEntityKeyRouteWithChildren =
  ApiStocksEntityKeyRoute._addFileChildren(ApiStocksEntityKeyRouteChildren)

interface ApiStocksRouteChildren {
  ApiStocksEntityKeyRoute: typeof ApiStocksEntityKeyRouteWithChildren
}

const ApiStocksRouteChildren: ApiStocksRouteChildren = {
  ApiStocksEntityKeyRoute: ApiStocksEntityKeyRouteWithChildren,
}

const ApiStocksRouteWithChildren = ApiStocksRoute._addFileChildren(
  ApiStocksRouteChildren,
)

interface ApiWatchlistRouteChildren {
  ApiWatchlistEntityKeyRoute: typeof ApiWatchlistEntityKeyRoute
}

const ApiWatchlistRouteChildren: ApiWatchlistRouteChildren = {
  ApiWatchlistEntityKeyRoute: ApiWatchlistEntityKeyRoute,
}

const ApiWatchlistRouteWithChildren = ApiWatchlistRoute._addFileChildren(
  ApiWatchlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiMarketNewsRoute: ApiMarketNewsRoute,
  ApiMyResearchRoute: ApiMyResearchRoute,
  ApiPositionsRoute: ApiPositionsRouteWithChildren,
  ApiRadarRoute: ApiRadarRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiStocksRoute: ApiStocksRouteWithChildren,
  ApiThemesRoute: ApiThemesRoute,
  ApiWatchlistRoute: ApiWatchlistRouteWithChildren,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiDashboardTodayRoute: ApiDashboardTodayRoute,
  ApiDiscoverStocksRoute: ApiDiscoverStocksRoute,
  ApiMeBootstrapRoute: ApiMeBootstrapRoute,
  ApiPortfolioDigestRoute: ApiPortfolioDigestRoute,
  ApiRecordsRecordKeyRoute: ApiRecordsRecordKeyRoute,
  ApiV1ConfirmationRoute: ApiV1ConfirmationRoute,
  ApiV1FeaturesRoute: ApiV1FeaturesRoute,
  ApiV1ImpactRoute: ApiV1ImpactRoute,
  ApiEntitiesEntityKeyRelationsRoute: ApiEntitiesEntityKeyRelationsRoute,
  ApiV1CalibrationScorecardRoute: ApiV1CalibrationScorecardRoute,
  ApiV1PersonalFeedRoute: ApiV1PersonalFeedRoute,
  ApiV1ReportsLatestRoute: ApiV1ReportsLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
