/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as Char91__uiLabChar93RouteImport } from './routes/[__ui-lab]'
import { Route as Char91__devPreviewChar93RouteImport } from './routes/[__dev-preview]'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiThemesRouteImport } from './routes/api/themes'
import { Route as ApiStocksRouteImport } from './routes/api/stocks'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiRadarRouteImport } from './routes/api/radar'
import { Route as ApiPositionsRouteImport } from './routes/api/positions'
import { Route as ApiMyResearchRouteImport } from './routes/api/my-research'
import { Route as ApiMarketNewsRouteImport } from './routes/api/market-news'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace/index'
import { Route as ApiWatchlistEntityKeyRouteImport } from './routes/api/watchlist/$entityKey'
import { Route as ApiV1ImpactRouteImport } from './routes/api/v1/impact'
import { Route as ApiV1FeaturesRouteImport } from './routes/api/v1/features'
import { Route as ApiV1ConfirmationRouteImport } from './routes/api/v1/confirmation'
import { Route as ApiStocksEntityKeyRouteImport } from './routes/api/stocks/$entityKey'
import { Route as ApiRecordsRecordKeyRouteImport } from './routes/api/records/$recordKey'
import { Route as ApiPositionsEntityKeyRouteImport } from './routes/api/positions/$entityKey'
import { Route as ApiPortfolioDigestRouteImport } from './routes/api/portfolio/digest'
import { Route as ApiMeBootstrapRouteImport } from './routes/api/me/bootstrap'
import { Route as ApiGeoSnapshotRouteImport } from './routes/api/geo/snapshot'
import { Route as ApiDiscoverStocksRouteImport } from './routes/api/discover/stocks'
import { Route as ApiDashboardTodayRouteImport } from './routes/api/dashboard/today'
import { Route as AuthenticatedWorkspaceTodayRouteImport } from './routes/_authenticated/workspace/today'
import { Route as AuthenticatedWorkspaceThemesRouteImport } from './routes/_authenticated/workspace/themes'
import { Route as AuthenticatedWorkspaceStocksRouteImport } from './routes/_authenticated/workspace/stocks'
import { Route as AuthenticatedWorkspaceStatusRouteImport } from './routes/_authenticated/workspace/status'
import { Route as AuthenticatedWorkspaceResearchRouteImport } from './routes/_authenticated/workspace/research'
import { Route as AuthenticatedWorkspaceRadarRouteImport } from './routes/_authenticated/workspace/radar'
import { Route as AuthenticatedWorkspaceMarketTopicNewsRouteImport } from './routes/_authenticated/workspace/market-topic-news'
import { Route as AuthenticatedWorkspaceHistoryRouteImport } from './routes/_authenticated/workspace/history'
import { Route as AuthenticatedWorkspaceCryptoRouteImport } from './routes/_authenticated/workspace/crypto'
import { Route as AuthenticatedAdminInvitationsRouteImport } from './routes/_authenticated/admin/invitations'
import { Route as ApiV1ReportsLatestRouteImport } from './routes/api/v1/reports/latest'
import { Route as ApiV1PersonalFeedRouteImport } from './routes/api/v1/personal/feed'
import { Route as ApiV1ImpactBriefRouteImport } from './routes/api/v1/impact/brief'
import { Route as ApiV1CryptoWorkspaceRouteImport } from './routes/api/v1/crypto/workspace'
import { Route as ApiV1CalibrationScorecardRouteImport } from './routes/api/v1/calibration/scorecard'
import { Route as ApiStocksEntityKeyPricesRouteImport } from './routes/api/stocks/$entityKey.prices'
import { Route as ApiEntitiesEntityKeyRelationsRouteImport } from './routes/api/entities/$entityKey/relations'
import { Route as ApiGeoTilesZXYRouteImport } from './routes/api/geo/tiles/$z/$x/$y'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__uiLabChar93Route = Char91__uiLabChar93RouteImport.update({
  id: '/__ui-lab',
  path: '/__ui-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__devPreviewChar93Route =
  Char91__devPreviewChar93RouteImport.update({
    id: '/__dev-preview',
    path: '/__dev-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemesRoute = ApiThemesRouteImport.update({
  id: '/api/themes',
  path: '/api/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksRoute = ApiStocksRouteImport.update({
  id: '/api/stocks',
  path: '/api/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadarRoute = ApiRadarRouteImport.update({
  id: '/api/radar',
  path: '/api/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPositionsRoute = ApiPositionsRouteImport.update({
  id: '/api/positions',
  path: '/api/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyResearchRoute = ApiMyResearchRouteImport.update({
  id: '/api/my-research',
  path: '/api/my-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketNewsRoute = ApiMarketNewsRouteImport.update({
  id: '/api/market-news',
  path: '/api/market-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const ApiWatchlistEntityKeyRoute = ApiWatchlistEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiWatchlistRoute,
} as any)
const ApiV1ImpactRoute = ApiV1ImpactRouteImport.update({
  id: '/api/v1/impact',
  path: '/api/v1/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FeaturesRoute = ApiV1FeaturesRouteImport.update({
  id: '/api/v1/features',
  path: '/api/v1/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConfirmationRoute = ApiV1ConfirmationRouteImport.update({
  id: '/api/v1/confirmation',
  path: '/api/v1/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksEntityKeyRoute = ApiStocksEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiStocksRoute,
} as any)
const ApiRecordsRecordKeyRoute = ApiRecordsRecordKeyRouteImport.update({
  id: '/api/records/$recordKey',
  path: '/api/records/$recordKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPositionsEntityKeyRoute = ApiPositionsEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiPositionsRoute,
} as any)
const ApiPortfolioDigestRoute = ApiPortfolioDigestRouteImport.update({
  id: '/api/portfolio/digest',
  path: '/api/portfolio/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBootstrapRoute = ApiMeBootstrapRouteImport.update({
  id: '/api/me/bootstrap',
  path: '/api/me/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoSnapshotRoute = ApiGeoSnapshotRouteImport.update({
  id: '/api/geo/snapshot',
  path: '/api/geo/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverStocksRoute = ApiDiscoverStocksRouteImport.update({
  id: '/api/discover/stocks',
  path: '/api/discover/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardTodayRoute = ApiDashboardTodayRouteImport.update({
  id: '/api/dashboard/today',
  path: '/api/dashboard/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceTodayRoute =
  AuthenticatedWorkspaceTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceThemesRoute =
  AuthenticatedWorkspaceThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceStocksRoute =
  AuthenticatedWorkspaceStocksRouteImport.update({
    id: '/stocks',
    path: '/stocks',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceStatusRoute =
  AuthenticatedWorkspaceStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceResearchRoute =
  AuthenticatedWorkspaceResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceRadarRoute =
  AuthenticatedWorkspaceRadarRouteImport.update({
    id: '/radar',
    path: '/radar',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceMarketTopicNewsRoute =
  AuthenticatedWorkspaceMarketTopicNewsRouteImport.update({
    id: '/market-topic-news',
    path: '/market-topic-news',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceHistoryRoute =
  AuthenticatedWorkspaceHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCryptoRoute =
  AuthenticatedWorkspaceCryptoRouteImport.update({
    id: '/crypto',
    path: '/crypto',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedAdminInvitationsRoute =
  AuthenticatedAdminInvitationsRouteImport.update({
    id: '/admin/invitations',
    path: '/admin/invitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1ReportsLatestRoute = ApiV1ReportsLatestRouteImport.update({
  id: '/api/v1/reports/latest',
  path: '/api/v1/reports/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PersonalFeedRoute = ApiV1PersonalFeedRouteImport.update({
  id: '/api/v1/personal/feed',
  path: '/api/v1/personal/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ImpactBriefRoute = ApiV1ImpactBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => ApiV1ImpactRoute,
} as any)
const ApiV1CryptoWorkspaceRoute = ApiV1CryptoWorkspaceRouteImport.update({
  id: '/api/v1/crypto/workspace',
  path: '/api/v1/crypto/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CalibrationScorecardRoute =
  ApiV1CalibrationScorecardRouteImport.update({
    id: '/api/v1/calibration/scorecard',
    path: '/api/v1/calibration/scorecard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStocksEntityKeyPricesRoute =
  ApiStocksEntityKeyPricesRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => ApiStocksEntityKeyRoute,
  } as any)
const ApiEntitiesEntityKeyRelationsRoute =
  ApiEntitiesEntityKeyRelationsRouteImport.update({
    id: '/api/entities/$entityKey/relations',
    path: '/api/entities/$entityKey/relations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGeoTilesZXYRoute = ApiGeoTilesZXYRouteImport.update({
  id: '/api/geo/tiles/$z/$x/$y',
  path: '/api/geo/tiles/$z/$x/$y',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/__dev-preview': typeof Char91__devPreviewChar93Route
  '/__ui-lab': typeof Char91__uiLabChar93Route
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/my-research': typeof ApiMyResearchRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/radar': typeof ApiRadarRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/themes': typeof ApiThemesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/workspace/crypto': typeof AuthenticatedWorkspaceCryptoRoute
  '/workspace/history': typeof AuthenticatedWorkspaceHistoryRoute
  '/workspace/market-topic-news': typeof AuthenticatedWorkspaceMarketTopicNewsRoute
  '/workspace/radar': typeof AuthenticatedWorkspaceRadarRoute
  '/workspace/research': typeof AuthenticatedWorkspaceResearchRoute
  '/workspace/status': typeof AuthenticatedWorkspaceStatusRoute
  '/workspace/stocks': typeof AuthenticatedWorkspaceStocksRoute
  '/workspace/themes': typeof AuthenticatedWorkspaceThemesRoute
  '/workspace/today': typeof AuthenticatedWorkspaceTodayRoute
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/geo/snapshot': typeof ApiGeoSnapshotRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/records/$recordKey': typeof ApiRecordsRecordKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRouteWithChildren
  '/api/v1/confirmation': typeof ApiV1ConfirmationRoute
  '/api/v1/features': typeof ApiV1FeaturesRoute
  '/api/v1/impact': typeof ApiV1ImpactRouteWithChildren
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/api/entities/$entityKey/relations': typeof ApiEntitiesEntityKeyRelationsRoute
  '/api/stocks/$entityKey/prices': typeof ApiStocksEntityKeyPricesRoute
  '/api/v1/calibration/scorecard': typeof ApiV1CalibrationScorecardRoute
  '/api/v1/crypto/workspace': typeof ApiV1CryptoWorkspaceRoute
  '/api/v1/impact/brief': typeof ApiV1ImpactBriefRoute
  '/api/v1/personal/feed': typeof ApiV1PersonalFeedRoute
  '/api/v1/reports/latest': typeof ApiV1ReportsLatestRoute
  '/api/geo/tiles/$z/$x/$y': typeof ApiGeoTilesZXYRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/__dev-preview': typeof Char91__devPreviewChar93Route
  '/__ui-lab': typeof Char91__uiLabChar93Route
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/my-research': typeof ApiMyResearchRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/radar': typeof ApiRadarRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/themes': typeof ApiThemesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/workspace/crypto': typeof AuthenticatedWorkspaceCryptoRoute
  '/workspace/history': typeof AuthenticatedWorkspaceHistoryRoute
  '/workspace/market-topic-news': typeof AuthenticatedWorkspaceMarketTopicNewsRoute
  '/workspace/radar': typeof AuthenticatedWorkspaceRadarRoute
  '/workspace/research': typeof AuthenticatedWorkspaceResearchRoute
  '/workspace/status': typeof AuthenticatedWorkspaceStatusRoute
  '/workspace/stocks': typeof AuthenticatedWorkspaceStocksRoute
  '/workspace/themes': typeof AuthenticatedWorkspaceThemesRoute
  '/workspace/today': typeof AuthenticatedWorkspaceTodayRoute
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/geo/snapshot': typeof ApiGeoSnapshotRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/records/$recordKey': typeof ApiRecordsRecordKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRouteWithChildren
  '/api/v1/confirmation': typeof ApiV1ConfirmationRoute
  '/api/v1/features': typeof ApiV1FeaturesRoute
  '/api/v1/impact': typeof ApiV1ImpactRouteWithChildren
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/api/entities/$entityKey/relations': typeof ApiEntitiesEntityKeyRelationsRoute
  '/api/stocks/$entityKey/prices': typeof ApiStocksEntityKeyPricesRoute
  '/api/v1/calibration/scorecard': typeof ApiV1CalibrationScorecardRoute
  '/api/v1/crypto/workspace': typeof ApiV1CryptoWorkspaceRoute
  '/api/v1/impact/brief': typeof ApiV1ImpactBriefRoute
  '/api/v1/personal/feed': typeof ApiV1PersonalFeedRoute
  '/api/v1/reports/latest': typeof ApiV1ReportsLatestRoute
  '/api/geo/tiles/$z/$x/$y': typeof ApiGeoTilesZXYRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__dev-preview': typeof Char91__devPreviewChar93Route
  '/__ui-lab': typeof Char91__uiLabChar93Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/my-research': typeof ApiMyResearchRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/radar': typeof ApiRadarRoute
  '/api/status': typeof ApiStatusRoute
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/themes': typeof ApiThemesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRoute
  '/_authenticated/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/_authenticated/workspace/crypto': typeof AuthenticatedWorkspaceCryptoRoute
  '/_authenticated/workspace/history': typeof AuthenticatedWorkspaceHistoryRoute
  '/_authenticated/workspace/market-topic-news': typeof AuthenticatedWorkspaceMarketTopicNewsRoute
  '/_authenticated/workspace/radar': typeof AuthenticatedWorkspaceRadarRoute
  '/_authenticated/workspace/research': typeof AuthenticatedWorkspaceResearchRoute
  '/_authenticated/workspace/status': typeof AuthenticatedWorkspaceStatusRoute
  '/_authenticated/workspace/stocks': typeof AuthenticatedWorkspaceStocksRoute
  '/_authenticated/workspace/themes': typeof AuthenticatedWorkspaceThemesRoute
  '/_authenticated/workspace/today': typeof AuthenticatedWorkspaceTodayRoute
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/geo/snapshot': typeof ApiGeoSnapshotRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/records/$recordKey': typeof ApiRecordsRecordKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRouteWithChildren
  '/api/v1/confirmation': typeof ApiV1ConfirmationRoute
  '/api/v1/features': typeof ApiV1FeaturesRoute
  '/api/v1/impact': typeof ApiV1ImpactRouteWithChildren
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/api/entities/$entityKey/relations': typeof ApiEntitiesEntityKeyRelationsRoute
  '/api/stocks/$entityKey/prices': typeof ApiStocksEntityKeyPricesRoute
  '/api/v1/calibration/scorecard': typeof ApiV1CalibrationScorecardRoute
  '/api/v1/crypto/workspace': typeof ApiV1CryptoWorkspaceRoute
  '/api/v1/impact/brief': typeof ApiV1ImpactBriefRoute
  '/api/v1/personal/feed': typeof ApiV1PersonalFeedRoute
  '/api/v1/reports/latest': typeof ApiV1ReportsLatestRoute
  '/api/geo/tiles/$z/$x/$y': typeof ApiGeoTilesZXYRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/__dev-preview'
    | '/__ui-lab'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/feed'
    | '/api/health'
    | '/api/history'
    | '/api/market-news'
    | '/api/my-research'
    | '/api/positions'
    | '/api/radar'
    | '/api/status'
    | '/api/stocks'
    | '/api/themes'
    | '/api/watchlist'
    | '/api/workspace'
    | '/admin/invitations'
    | '/workspace/crypto'
    | '/workspace/history'
    | '/workspace/market-topic-news'
    | '/workspace/radar'
    | '/workspace/research'
    | '/workspace/status'
    | '/workspace/stocks'
    | '/workspace/themes'
    | '/workspace/today'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/geo/snapshot'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/records/$recordKey'
    | '/api/stocks/$entityKey'
    | '/api/v1/confirmation'
    | '/api/v1/features'
    | '/api/v1/impact'
    | '/api/watchlist/$entityKey'
    | '/workspace/'
    | '/api/entities/$entityKey/relations'
    | '/api/stocks/$entityKey/prices'
    | '/api/v1/calibration/scorecard'
    | '/api/v1/crypto/workspace'
    | '/api/v1/impact/brief'
    | '/api/v1/personal/feed'
    | '/api/v1/reports/latest'
    | '/api/geo/tiles/$z/$x/$y'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/__dev-preview'
    | '/__ui-lab'
    | '/login'
    | '/signup'
    | '/api/feed'
    | '/api/health'
    | '/api/history'
    | '/api/market-news'
    | '/api/my-research'
    | '/api/positions'
    | '/api/radar'
    | '/api/status'
    | '/api/stocks'
    | '/api/themes'
    | '/api/watchlist'
    | '/api/workspace'
    | '/admin/invitations'
    | '/workspace/crypto'
    | '/workspace/history'
    | '/workspace/market-topic-news'
    | '/workspace/radar'
    | '/workspace/research'
    | '/workspace/status'
    | '/workspace/stocks'
    | '/workspace/themes'
    | '/workspace/today'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/geo/snapshot'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/records/$recordKey'
    | '/api/stocks/$entityKey'
    | '/api/v1/confirmation'
    | '/api/v1/features'
    | '/api/v1/impact'
    | '/api/watchlist/$entityKey'
    | '/workspace'
    | '/api/entities/$entityKey/relations'
    | '/api/stocks/$entityKey/prices'
    | '/api/v1/calibration/scorecard'
    | '/api/v1/crypto/workspace'
    | '/api/v1/impact/brief'
    | '/api/v1/personal/feed'
    | '/api/v1/reports/latest'
    | '/api/geo/tiles/$z/$x/$y'
  id:
    | '__root__'
    | '/'
    | '/__dev-preview'
    | '/__ui-lab'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/workspace'
    | '/api/feed'
    | '/api/health'
    | '/api/history'
    | '/api/market-news'
    | '/api/my-research'
    | '/api/positions'
    | '/api/radar'
    | '/api/status'
    | '/api/stocks'
    | '/api/themes'
    | '/api/watchlist'
    | '/api/workspace'
    | '/_authenticated/admin/invitations'
    | '/_authenticated/workspace/crypto'
    | '/_authenticated/workspace/history'
    | '/_authenticated/workspace/market-topic-news'
    | '/_authenticated/workspace/radar'
    | '/_authenticated/workspace/research'
    | '/_authenticated/workspace/status'
    | '/_authenticated/workspace/stocks'
    | '/_authenticated/workspace/themes'
    | '/_authenticated/workspace/today'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/geo/snapshot'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/records/$recordKey'
    | '/api/stocks/$entityKey'
    | '/api/v1/confirmation'
    | '/api/v1/features'
    | '/api/v1/impact'
    | '/api/watchlist/$entityKey'
    | '/_authenticated/workspace/'
    | '/api/entities/$entityKey/relations'
    | '/api/stocks/$entityKey/prices'
    | '/api/v1/calibration/scorecard'
    | '/api/v1/crypto/workspace'
    | '/api/v1/impact/brief'
    | '/api/v1/personal/feed'
    | '/api/v1/reports/latest'
    | '/api/geo/tiles/$z/$x/$y'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91__devPreviewChar93Route: typeof Char91__devPreviewChar93Route
  Char91__uiLabChar93Route: typeof Char91__uiLabChar93Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiMarketNewsRoute: typeof ApiMarketNewsRoute
  ApiMyResearchRoute: typeof ApiMyResearchRoute
  ApiPositionsRoute: typeof ApiPositionsRouteWithChildren
  ApiRadarRoute: typeof ApiRadarRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiStocksRoute: typeof ApiStocksRouteWithChildren
  ApiThemesRoute: typeof ApiThemesRoute
  ApiWatchlistRoute: typeof ApiWatchlistRouteWithChildren
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiDashboardTodayRoute: typeof ApiDashboardTodayRoute
  ApiDiscoverStocksRoute: typeof ApiDiscoverStocksRoute
  ApiGeoSnapshotRoute: typeof ApiGeoSnapshotRoute
  ApiMeBootstrapRoute: typeof ApiMeBootstrapRoute
  ApiPortfolioDigestRoute: typeof ApiPortfolioDigestRoute
  ApiRecordsRecordKeyRoute: typeof ApiRecordsRecordKeyRoute
  ApiV1ConfirmationRoute: typeof ApiV1ConfirmationRoute
  ApiV1FeaturesRoute: typeof ApiV1FeaturesRoute
  ApiV1ImpactRoute: typeof ApiV1ImpactRouteWithChildren
  ApiEntitiesEntityKeyRelationsRoute: typeof ApiEntitiesEntityKeyRelationsRoute
  ApiV1CalibrationScorecardRoute: typeof ApiV1CalibrationScorecardRoute
  ApiV1CryptoWorkspaceRoute: typeof ApiV1CryptoWorkspaceRoute
  ApiV1PersonalFeedRoute: typeof ApiV1PersonalFeedRoute
  ApiV1ReportsLatestRoute: typeof ApiV1ReportsLatestRoute
  ApiGeoTilesZXYRoute: typeof ApiGeoTilesZXYRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__ui-lab': {
      id: '/__ui-lab'
      path: '/__ui-lab'
      fullPath: '/__ui-lab'
      preLoaderRoute: typeof Char91__uiLabChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dev-preview': {
      id: '/__dev-preview'
      path: '/__dev-preview'
      fullPath: '/__dev-preview'
      preLoaderRoute: typeof Char91__devPreviewChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/themes': {
      id: '/api/themes'
      path: '/api/themes'
      fullPath: '/api/themes'
      preLoaderRoute: typeof ApiThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks': {
      id: '/api/stocks'
      path: '/api/stocks'
      fullPath: '/api/stocks'
      preLoaderRoute: typeof ApiStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radar': {
      id: '/api/radar'
      path: '/api/radar'
      fullPath: '/api/radar'
      preLoaderRoute: typeof ApiRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/positions': {
      id: '/api/positions'
      path: '/api/positions'
      fullPath: '/api/positions'
      preLoaderRoute: typeof ApiPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-research': {
      id: '/api/my-research'
      path: '/api/my-research'
      fullPath: '/api/my-research'
      preLoaderRoute: typeof ApiMyResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-news': {
      id: '/api/market-news'
      path: '/api/market-news'
      fullPath: '/api/market-news'
      preLoaderRoute: typeof ApiMarketNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/api/watchlist/$entityKey': {
      id: '/api/watchlist/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/watchlist/$entityKey'
      preLoaderRoute: typeof ApiWatchlistEntityKeyRouteImport
      parentRoute: typeof ApiWatchlistRoute
    }
    '/api/v1/impact': {
      id: '/api/v1/impact'
      path: '/api/v1/impact'
      fullPath: '/api/v1/impact'
      preLoaderRoute: typeof ApiV1ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/features': {
      id: '/api/v1/features'
      path: '/api/v1/features'
      fullPath: '/api/v1/features'
      preLoaderRoute: typeof ApiV1FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/confirmation': {
      id: '/api/v1/confirmation'
      path: '/api/v1/confirmation'
      fullPath: '/api/v1/confirmation'
      preLoaderRoute: typeof ApiV1ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks/$entityKey': {
      id: '/api/stocks/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/stocks/$entityKey'
      preLoaderRoute: typeof ApiStocksEntityKeyRouteImport
      parentRoute: typeof ApiStocksRoute
    }
    '/api/records/$recordKey': {
      id: '/api/records/$recordKey'
      path: '/api/records/$recordKey'
      fullPath: '/api/records/$recordKey'
      preLoaderRoute: typeof ApiRecordsRecordKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/positions/$entityKey': {
      id: '/api/positions/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/positions/$entityKey'
      preLoaderRoute: typeof ApiPositionsEntityKeyRouteImport
      parentRoute: typeof ApiPositionsRoute
    }
    '/api/portfolio/digest': {
      id: '/api/portfolio/digest'
      path: '/api/portfolio/digest'
      fullPath: '/api/portfolio/digest'
      preLoaderRoute: typeof ApiPortfolioDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/bootstrap': {
      id: '/api/me/bootstrap'
      path: '/api/me/bootstrap'
      fullPath: '/api/me/bootstrap'
      preLoaderRoute: typeof ApiMeBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/snapshot': {
      id: '/api/geo/snapshot'
      path: '/api/geo/snapshot'
      fullPath: '/api/geo/snapshot'
      preLoaderRoute: typeof ApiGeoSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover/stocks': {
      id: '/api/discover/stocks'
      path: '/api/discover/stocks'
      fullPath: '/api/discover/stocks'
      preLoaderRoute: typeof ApiDiscoverStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/today': {
      id: '/api/dashboard/today'
      path: '/api/dashboard/today'
      fullPath: '/api/dashboard/today'
      preLoaderRoute: typeof ApiDashboardTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/today': {
      id: '/_authenticated/workspace/today'
      path: '/today'
      fullPath: '/workspace/today'
      preLoaderRoute: typeof AuthenticatedWorkspaceTodayRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/themes': {
      id: '/_authenticated/workspace/themes'
      path: '/themes'
      fullPath: '/workspace/themes'
      preLoaderRoute: typeof AuthenticatedWorkspaceThemesRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/stocks': {
      id: '/_authenticated/workspace/stocks'
      path: '/stocks'
      fullPath: '/workspace/stocks'
      preLoaderRoute: typeof AuthenticatedWorkspaceStocksRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/status': {
      id: '/_authenticated/workspace/status'
      path: '/status'
      fullPath: '/workspace/status'
      preLoaderRoute: typeof AuthenticatedWorkspaceStatusRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/research': {
      id: '/_authenticated/workspace/research'
      path: '/research'
      fullPath: '/workspace/research'
      preLoaderRoute: typeof AuthenticatedWorkspaceResearchRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/radar': {
      id: '/_authenticated/workspace/radar'
      path: '/radar'
      fullPath: '/workspace/radar'
      preLoaderRoute: typeof AuthenticatedWorkspaceRadarRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/market-topic-news': {
      id: '/_authenticated/workspace/market-topic-news'
      path: '/market-topic-news'
      fullPath: '/workspace/market-topic-news'
      preLoaderRoute: typeof AuthenticatedWorkspaceMarketTopicNewsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/history': {
      id: '/_authenticated/workspace/history'
      path: '/history'
      fullPath: '/workspace/history'
      preLoaderRoute: typeof AuthenticatedWorkspaceHistoryRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/crypto': {
      id: '/_authenticated/workspace/crypto'
      path: '/crypto'
      fullPath: '/workspace/crypto'
      preLoaderRoute: typeof AuthenticatedWorkspaceCryptoRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/admin/invitations': {
      id: '/_authenticated/admin/invitations'
      path: '/admin/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthenticatedAdminInvitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/reports/latest': {
      id: '/api/v1/reports/latest'
      path: '/api/v1/reports/latest'
      fullPath: '/api/v1/reports/latest'
      preLoaderRoute: typeof ApiV1ReportsLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/personal/feed': {
      id: '/api/v1/personal/feed'
      path: '/api/v1/personal/feed'
      fullPath: '/api/v1/personal/feed'
      preLoaderRoute: typeof ApiV1PersonalFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/impact/brief': {
      id: '/api/v1/impact/brief'
      path: '/brief'
      fullPath: '/api/v1/impact/brief'
      preLoaderRoute: typeof ApiV1ImpactBriefRouteImport
      parentRoute: typeof ApiV1ImpactRoute
    }
    '/api/v1/crypto/workspace': {
      id: '/api/v1/crypto/workspace'
      path: '/api/v1/crypto/workspace'
      fullPath: '/api/v1/crypto/workspace'
      preLoaderRoute: typeof ApiV1CryptoWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calibration/scorecard': {
      id: '/api/v1/calibration/scorecard'
      path: '/api/v1/calibration/scorecard'
      fullPath: '/api/v1/calibration/scorecard'
      preLoaderRoute: typeof ApiV1CalibrationScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks/$entityKey/prices': {
      id: '/api/stocks/$entityKey/prices'
      path: '/prices'
      fullPath: '/api/stocks/$entityKey/prices'
      preLoaderRoute: typeof ApiStocksEntityKeyPricesRouteImport
      parentRoute: typeof ApiStocksEntityKeyRoute
    }
    '/api/entities/$entityKey/relations': {
      id: '/api/entities/$entityKey/relations'
      path: '/api/entities/$entityKey/relations'
      fullPath: '/api/entities/$entityKey/relations'
      preLoaderRoute: typeof ApiEntitiesEntityKeyRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/tiles/$z/$x/$y': {
      id: '/api/geo/tiles/$z/$x/$y'
      path: '/api/geo/tiles/$z/$x/$y'
      fullPath: '/api/geo/tiles/$z/$x/$y'
      preLoaderRoute: typeof ApiGeoTilesZXYRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceCryptoRoute: typeof AuthenticatedWorkspaceCryptoRoute
  AuthenticatedWorkspaceHistoryRoute: typeof AuthenticatedWorkspaceHistoryRoute
  AuthenticatedWorkspaceMarketTopicNewsRoute: typeof AuthenticatedWorkspaceMarketTopicNewsRoute
  AuthenticatedWorkspaceRadarRoute: typeof AuthenticatedWorkspaceRadarRoute
  AuthenticatedWorkspaceResearchRoute: typeof AuthenticatedWorkspaceResearchRoute
  AuthenticatedWorkspaceStatusRoute: typeof AuthenticatedWorkspaceStatusRoute
  AuthenticatedWorkspaceStocksRoute: typeof AuthenticatedWorkspaceStocksRoute
  AuthenticatedWorkspaceThemesRoute: typeof AuthenticatedWorkspaceThemesRoute
  AuthenticatedWorkspaceTodayRoute: typeof AuthenticatedWorkspaceTodayRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceCryptoRoute: AuthenticatedWorkspaceCryptoRoute,
    AuthenticatedWorkspaceHistoryRoute: AuthenticatedWorkspaceHistoryRoute,
    AuthenticatedWorkspaceMarketTopicNewsRoute:
      AuthenticatedWorkspaceMarketTopicNewsRoute,
    AuthenticatedWorkspaceRadarRoute: AuthenticatedWorkspaceRadarRoute,
    AuthenticatedWorkspaceResearchRoute: AuthenticatedWorkspaceResearchRoute,
    AuthenticatedWorkspaceStatusRoute: AuthenticatedWorkspaceStatusRoute,
    AuthenticatedWorkspaceStocksRoute: AuthenticatedWorkspaceStocksRoute,
    AuthenticatedWorkspaceThemesRoute: AuthenticatedWorkspaceThemesRoute,
    AuthenticatedWorkspaceTodayRoute: AuthenticatedWorkspaceTodayRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedAdminInvitationsRoute: typeof AuthenticatedAdminInvitationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedAdminInvitationsRoute: AuthenticatedAdminInvitationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPositionsRouteChildren {
  ApiPositionsEntityKeyRoute: typeof ApiPositionsEntityKeyRoute
}

const ApiPositionsRouteChildren: ApiPositionsRouteChildren = {
  ApiPositionsEntityKeyRoute: ApiPositionsEntityKeyRoute,
}

const ApiPositionsRouteWithChildren = ApiPositionsRoute._addFileChildren(
  ApiPositionsRouteChildren,
)

interface ApiStocksEntityKeyRouteChildren {
  ApiStocksEntityKeyPricesRoute: typeof ApiStocksEntityKeyPricesRoute
}

const ApiStocksEntityKeyRouteChildren: ApiStocksEntityKeyRouteChildren = {
  ApiStocksEntityKeyPricesRoute: ApiStocksEntityKeyPricesRoute,
}

const ApiStocksEntityKeyRouteWithChildren =
  ApiStocksEntityKeyRoute._addFileChildren(ApiStocksEntityKeyRouteChildren)

interface ApiStocksRouteChildren {
  ApiStocksEntityKeyRoute: typeof ApiStocksEntityKeyRouteWithChildren
}

const ApiStocksRouteChildren: ApiStocksRouteChildren = {
  ApiStocksEntityKeyRoute: ApiStocksEntityKeyRouteWithChildren,
}

const ApiStocksRouteWithChildren = ApiStocksRoute._addFileChildren(
  ApiStocksRouteChildren,
)

interface ApiWatchlistRouteChildren {
  ApiWatchlistEntityKeyRoute: typeof ApiWatchlistEntityKeyRoute
}

const ApiWatchlistRouteChildren: ApiWatchlistRouteChildren = {
  ApiWatchlistEntityKeyRoute: ApiWatchlistEntityKeyRoute,
}

const ApiWatchlistRouteWithChildren = ApiWatchlistRoute._addFileChildren(
  ApiWatchlistRouteChildren,
)

interface ApiV1ImpactRouteChildren {
  ApiV1ImpactBriefRoute: typeof ApiV1ImpactBriefRoute
}

const ApiV1ImpactRouteChildren: ApiV1ImpactRouteChildren = {
  ApiV1ImpactBriefRoute: ApiV1ImpactBriefRoute,
}

const ApiV1ImpactRouteWithChildren = ApiV1ImpactRoute._addFileChildren(
  ApiV1ImpactRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91__devPreviewChar93Route: Char91__devPreviewChar93Route,
  Char91__uiLabChar93Route: Char91__uiLabChar93Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiMarketNewsRoute: ApiMarketNewsRoute,
  ApiMyResearchRoute: ApiMyResearchRoute,
  ApiPositionsRoute: ApiPositionsRouteWithChildren,
  ApiRadarRoute: ApiRadarRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiStocksRoute: ApiStocksRouteWithChildren,
  ApiThemesRoute: ApiThemesRoute,
  ApiWatchlistRoute: ApiWatchlistRouteWithChildren,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiDashboardTodayRoute: ApiDashboardTodayRoute,
  ApiDiscoverStocksRoute: ApiDiscoverStocksRoute,
  ApiGeoSnapshotRoute: ApiGeoSnapshotRoute,
  ApiMeBootstrapRoute: ApiMeBootstrapRoute,
  ApiPortfolioDigestRoute: ApiPortfolioDigestRoute,
  ApiRecordsRecordKeyRoute: ApiRecordsRecordKeyRoute,
  ApiV1ConfirmationRoute: ApiV1ConfirmationRoute,
  ApiV1FeaturesRoute: ApiV1FeaturesRoute,
  ApiV1ImpactRoute: ApiV1ImpactRouteWithChildren,
  ApiEntitiesEntityKeyRelationsRoute: ApiEntitiesEntityKeyRelationsRoute,
  ApiV1CalibrationScorecardRoute: ApiV1CalibrationScorecardRoute,
  ApiV1CryptoWorkspaceRoute: ApiV1CryptoWorkspaceRoute,
  ApiV1PersonalFeedRoute: ApiV1PersonalFeedRoute,
  ApiV1ReportsLatestRoute: ApiV1ReportsLatestRoute,
  ApiGeoTilesZXYRoute: ApiGeoTilesZXYRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
