/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiStocksRouteImport } from './routes/api/stocks'
import { Route as ApiPositionsRouteImport } from './routes/api/positions'
import { Route as ApiMarketNewsRouteImport } from './routes/api/market-news'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiWatchlistEntityKeyRouteImport } from './routes/api/watchlist/$entityKey'
import { Route as ApiStocksEntityKeyRouteImport } from './routes/api/stocks/$entityKey'
import { Route as ApiPositionsEntityKeyRouteImport } from './routes/api/positions/$entityKey'
import { Route as ApiPortfolioDigestRouteImport } from './routes/api/portfolio/digest'
import { Route as ApiMeBootstrapRouteImport } from './routes/api/me/bootstrap'
import { Route as ApiDiscoverStocksRouteImport } from './routes/api/discover/stocks'
import { Route as ApiDashboardTodayRouteImport } from './routes/api/dashboard/today'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksRoute = ApiStocksRouteImport.update({
  id: '/api/stocks',
  path: '/api/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPositionsRoute = ApiPositionsRouteImport.update({
  id: '/api/positions',
  path: '/api/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketNewsRoute = ApiMarketNewsRouteImport.update({
  id: '/api/market-news',
  path: '/api/market-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistEntityKeyRoute = ApiWatchlistEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiWatchlistRoute,
} as any)
const ApiStocksEntityKeyRoute = ApiStocksEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiStocksRoute,
} as any)
const ApiPositionsEntityKeyRoute = ApiPositionsEntityKeyRouteImport.update({
  id: '/$entityKey',
  path: '/$entityKey',
  getParentRoute: () => ApiPositionsRoute,
} as any)
const ApiPortfolioDigestRoute = ApiPortfolioDigestRouteImport.update({
  id: '/api/portfolio/digest',
  path: '/api/portfolio/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBootstrapRoute = ApiMeBootstrapRouteImport.update({
  id: '/api/me/bootstrap',
  path: '/api/me/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverStocksRoute = ApiDiscoverStocksRouteImport.update({
  id: '/api/discover/stocks',
  path: '/api/discover/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardTodayRoute = ApiDashboardTodayRouteImport.update({
  id: '/api/dashboard/today',
  path: '/api/dashboard/today',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRoute
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRoute
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/stocks': typeof ApiStocksRouteWithChildren
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/dashboard/today': typeof ApiDashboardTodayRoute
  '/api/discover/stocks': typeof ApiDiscoverStocksRoute
  '/api/me/bootstrap': typeof ApiMeBootstrapRoute
  '/api/portfolio/digest': typeof ApiPortfolioDigestRoute
  '/api/positions/$entityKey': typeof ApiPositionsEntityKeyRoute
  '/api/stocks/$entityKey': typeof ApiStocksEntityKeyRoute
  '/api/watchlist/$entityKey': typeof ApiWatchlistEntityKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/market-news'
    | '/api/positions'
    | '/api/stocks'
    | '/api/watchlist'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/stocks/$entityKey'
    | '/api/watchlist/$entityKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/market-news'
    | '/api/positions'
    | '/api/stocks'
    | '/api/watchlist'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/stocks/$entityKey'
    | '/api/watchlist/$entityKey'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/market-news'
    | '/api/positions'
    | '/api/stocks'
    | '/api/watchlist'
    | '/api/dashboard/today'
    | '/api/discover/stocks'
    | '/api/me/bootstrap'
    | '/api/portfolio/digest'
    | '/api/positions/$entityKey'
    | '/api/stocks/$entityKey'
    | '/api/watchlist/$entityKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMarketNewsRoute: typeof ApiMarketNewsRoute
  ApiPositionsRoute: typeof ApiPositionsRouteWithChildren
  ApiStocksRoute: typeof ApiStocksRouteWithChildren
  ApiWatchlistRoute: typeof ApiWatchlistRouteWithChildren
  ApiDashboardTodayRoute: typeof ApiDashboardTodayRoute
  ApiDiscoverStocksRoute: typeof ApiDiscoverStocksRoute
  ApiMeBootstrapRoute: typeof ApiMeBootstrapRoute
  ApiPortfolioDigestRoute: typeof ApiPortfolioDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks': {
      id: '/api/stocks'
      path: '/api/stocks'
      fullPath: '/api/stocks'
      preLoaderRoute: typeof ApiStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/positions': {
      id: '/api/positions'
      path: '/api/positions'
      fullPath: '/api/positions'
      preLoaderRoute: typeof ApiPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-news': {
      id: '/api/market-news'
      path: '/api/market-news'
      fullPath: '/api/market-news'
      preLoaderRoute: typeof ApiMarketNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist/$entityKey': {
      id: '/api/watchlist/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/watchlist/$entityKey'
      preLoaderRoute: typeof ApiWatchlistEntityKeyRouteImport
      parentRoute: typeof ApiWatchlistRoute
    }
    '/api/stocks/$entityKey': {
      id: '/api/stocks/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/stocks/$entityKey'
      preLoaderRoute: typeof ApiStocksEntityKeyRouteImport
      parentRoute: typeof ApiStocksRoute
    }
    '/api/positions/$entityKey': {
      id: '/api/positions/$entityKey'
      path: '/$entityKey'
      fullPath: '/api/positions/$entityKey'
      preLoaderRoute: typeof ApiPositionsEntityKeyRouteImport
      parentRoute: typeof ApiPositionsRoute
    }
    '/api/portfolio/digest': {
      id: '/api/portfolio/digest'
      path: '/api/portfolio/digest'
      fullPath: '/api/portfolio/digest'
      preLoaderRoute: typeof ApiPortfolioDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/bootstrap': {
      id: '/api/me/bootstrap'
      path: '/api/me/bootstrap'
      fullPath: '/api/me/bootstrap'
      preLoaderRoute: typeof ApiMeBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover/stocks': {
      id: '/api/discover/stocks'
      path: '/api/discover/stocks'
      fullPath: '/api/discover/stocks'
      preLoaderRoute: typeof ApiDiscoverStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/today': {
      id: '/api/dashboard/today'
      path: '/api/dashboard/today'
      fullPath: '/api/dashboard/today'
      preLoaderRoute: typeof ApiDashboardTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPositionsRouteChildren {
  ApiPositionsEntityKeyRoute: typeof ApiPositionsEntityKeyRoute
}

const ApiPositionsRouteChildren: ApiPositionsRouteChildren = {
  ApiPositionsEntityKeyRoute: ApiPositionsEntityKeyRoute,
}

const ApiPositionsRouteWithChildren = ApiPositionsRoute._addFileChildren(
  ApiPositionsRouteChildren,
)

interface ApiStocksRouteChildren {
  ApiStocksEntityKeyRoute: typeof ApiStocksEntityKeyRoute
}

const ApiStocksRouteChildren: ApiStocksRouteChildren = {
  ApiStocksEntityKeyRoute: ApiStocksEntityKeyRoute,
}

const ApiStocksRouteWithChildren = ApiStocksRoute._addFileChildren(
  ApiStocksRouteChildren,
)

interface ApiWatchlistRouteChildren {
  ApiWatchlistEntityKeyRoute: typeof ApiWatchlistEntityKeyRoute
}

const ApiWatchlistRouteChildren: ApiWatchlistRouteChildren = {
  ApiWatchlistEntityKeyRoute: ApiWatchlistEntityKeyRoute,
}

const ApiWatchlistRouteWithChildren = ApiWatchlistRoute._addFileChildren(
  ApiWatchlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMarketNewsRoute: ApiMarketNewsRoute,
  ApiPositionsRoute: ApiPositionsRouteWithChildren,
  ApiStocksRoute: ApiStocksRouteWithChildren,
  ApiWatchlistRoute: ApiWatchlistRouteWithChildren,
  ApiDashboardTodayRoute: ApiDashboardTodayRoute,
  ApiDiscoverStocksRoute: ApiDiscoverStocksRoute,
  ApiMeBootstrapRoute: ApiMeBootstrapRoute,
  ApiPortfolioDigestRoute: ApiPortfolioDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
