export const appResearchFoundationMigrationSql = `
CREATE TABLE IF NOT EXISTS public.company_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_key text NOT NULL REFERENCES public.entities(entity_key),
  symbol text,
  market text,
  name text,
  sector text,
  industry text,
  summary_text text,
  profile_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  availability text NOT NULL DEFAULT 'missing' CHECK (availability in ('available', 'missing', 'collecting', 'stale', 'text_only', 'unsupported', 'error')),
  captured_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (entity_key)
);

CREATE TABLE IF NOT EXISTS public.company_financials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_key text NOT NULL REFERENCES public.entities(entity_key),
  fiscal_year integer,
  fiscal_period text,
  metric_group text NOT NULL DEFAULT 'summary',
  currency text,
  metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  availability text NOT NULL DEFAULT 'missing' CHECK (availability in ('available', 'missing', 'collecting', 'stale', 'text_only', 'unsupported', 'error')),
  reported_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (entity_key, fiscal_year, fiscal_period, metric_group)
);

CREATE TABLE IF NOT EXISTS public.analysis_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_key text NOT NULL UNIQUE,
  entity_key text NOT NULL REFERENCES public.entities(entity_key),
  status text NOT NULL DEFAULT 'queued' CHECK (status in ('queued', 'running', 'completed', 'failed', 'cancelled')),
  requested_scope text NOT NULL DEFAULT 'deep_analysis',
  priority integer NOT NULL DEFAULT 0,
  idempotency_key text UNIQUE,
  requested_by text,
  progress_pct numeric(5,2) NOT NULL DEFAULT 0 CHECK (progress_pct >= 0 AND progress_pct <= 100),
  error_code text,
  error_message text,
  result_deep_cache_key text,
  queued_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.analysis_job_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id bigint NOT NULL REFERENCES public.analysis_jobs(id),
  event_key text,
  event_type text NOT NULL,
  message text,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, event_key)
);

CREATE TABLE IF NOT EXISTS public.stock_learning_cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_key text NOT NULL REFERENCES public.entities(entity_key),
  card_key text NOT NULL,
  section text NOT NULL,
  title text NOT NULL,
  body_markdown text,
  bullets_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  availability text NOT NULL DEFAULT 'missing' CHECK (availability in ('available', 'missing', 'collecting', 'stale', 'text_only', 'unsupported', 'error')),
  source_kind text,
  source_uri text,
  derived_from_deep_cache boolean NOT NULL DEFAULT false,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (entity_key, card_key)
);

CREATE TABLE IF NOT EXISTS public.entity_glossary_terms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_key text REFERENCES public.entities(entity_key),
  term text NOT NULL,
  normalized_term text NOT NULL,
  definition text NOT NULL,
  source_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (entity_key, normalized_term)
);

CREATE TABLE IF NOT EXISTS public.user_notification_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL DEFAULT 'default',
  rule_key text NOT NULL,
  scope text NOT NULL DEFAULT 'portfolio_digest' CHECK (scope in ('portfolio_digest', 'stock_detail', 'freshness')),
  channel text NOT NULL DEFAULT 'in_app' CHECK (channel in ('in_app', 'discord', 'telegram')),
  enabled boolean NOT NULL DEFAULT true,
  severity_threshold text NOT NULL DEFAULT 'low' CHECK (severity_threshold in ('low', 'medium', 'high')),
  stock_only boolean NOT NULL DEFAULT true,
  rate_limit_minutes integer NOT NULL DEFAULT 60 CHECK (rate_limit_minutes >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, rule_key)
);

CREATE TABLE IF NOT EXISTS public.user_alert_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL DEFAULT 'default',
  rule_key text NOT NULL,
  event_key text NOT NULL,
  entity_key text REFERENCES public.entities(entity_key),
  market text CHECK (market is null or market in ('KR', 'US')),
  severity text NOT NULL CHECK (severity in ('low', 'medium', 'high')),
  reason text NOT NULL CHECK (reason in ('change_event', 'feed_change', 'freshness', 'exposure')),
  title text NOT NULL,
  summary text NOT NULL,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_kind text,
  source_ref text,
  occurred_at timestamptz,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, event_key)
);

CREATE TABLE IF NOT EXISTS public.user_decision_journal_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL DEFAULT 'default',
  entry_key text NOT NULL,
  entity_key text NOT NULL REFERENCES public.entities(entity_key),
  market text NOT NULL CHECK (market in ('KR', 'US')),
  entry_type text NOT NULL DEFAULT 'alert_review' CHECK (entry_type in ('alert_review', 'trade_note', 'judgment_evaluation', 'manual_note')),
  title text NOT NULL,
  thesis_text text NOT NULL,
  evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_kind text,
  source_ref text,
  occurred_at timestamptz,
  review_due_at timestamptz,
  status text NOT NULL DEFAULT 'open' CHECK (status in ('open', 'reviewed', 'archived')),
  advice_prohibited boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (advice_prohibited is true),
  UNIQUE (user_id, entry_key)
);

CREATE INDEX IF NOT EXISTS analysis_jobs_entity_status_idx
  ON public.analysis_jobs (entity_key, status, queued_at DESC);

CREATE INDEX IF NOT EXISTS analysis_job_events_job_created_idx
  ON public.analysis_job_events (job_id, created_at DESC);

CREATE INDEX IF NOT EXISTS stock_learning_cards_entity_section_idx
  ON public.stock_learning_cards (entity_key, section, updated_at DESC);

CREATE INDEX IF NOT EXISTS entity_glossary_terms_normalized_idx
  ON public.entity_glossary_terms (normalized_term);

CREATE INDEX IF NOT EXISTS user_notification_rules_user_enabled_idx
  ON public.user_notification_rules (user_id, enabled, scope);

CREATE INDEX IF NOT EXISTS user_alert_events_user_recorded_idx
  ON public.user_alert_events (user_id, recorded_at DESC);

CREATE INDEX IF NOT EXISTS user_alert_events_entity_recorded_idx
  ON public.user_alert_events (entity_key, recorded_at DESC);

CREATE INDEX IF NOT EXISTS user_decision_journal_user_status_idx
  ON public.user_decision_journal_entries (user_id, status, occurred_at DESC NULLS LAST, id DESC);

CREATE INDEX IF NOT EXISTS user_decision_journal_entity_idx
  ON public.user_decision_journal_entries (entity_key, occurred_at DESC NULLS LAST, id DESC);

CREATE OR REPLACE VIEW public.v_user_decision_journal AS
SELECT
  journal.id,
  journal.user_id,
  journal.entry_key,
  journal.entity_key,
  journal.market,
  journal.entry_type,
  journal.title,
  journal.thesis_text,
  journal.evidence_json,
  journal.source_kind,
  journal.source_ref,
  journal.occurred_at,
  journal.review_due_at,
  journal.status,
  journal.advice_prohibited,
  journal.created_at,
  journal.updated_at,
  entity.name AS entity_name,
  entity.symbol AS symbol
FROM public.user_decision_journal_entries journal
LEFT JOIN public.entities entity
  ON entity.entity_key = journal.entity_key;

CREATE OR REPLACE VIEW public.v_stock_learning_status AS
WITH latest_job AS (
  SELECT DISTINCT ON (entity_key)
    entity_key,
    id AS analysis_job_id,
    status AS analysis_status,
    progress_pct,
    queued_at,
    started_at,
    completed_at,
    error_code,
    error_message
  FROM public.analysis_jobs
  ORDER BY entity_key, queued_at DESC, id DESC
), card_counts AS (
  SELECT
    entity_key,
    count(*)::integer AS learning_card_count,
    max(updated_at) AS latest_learning_card_at,
    bool_or(availability = 'available') AS has_available_learning_card
  FROM public.stock_learning_cards
  GROUP BY entity_key
)
SELECT
  entity.entity_key,
  coalesce(job.analysis_status, CASE WHEN coalesce(cards.learning_card_count, 0) > 0 THEN 'completed' ELSE 'none' END) AS analysis_status,
  job.analysis_job_id,
  job.progress_pct,
  job.queued_at,
  job.started_at,
  job.completed_at,
  job.error_code,
  job.error_message,
  coalesce(cards.learning_card_count, 0) AS learning_card_count,
  coalesce(cards.has_available_learning_card, false) AS has_available_learning_card,
  cards.latest_learning_card_at
FROM public.entities entity
LEFT JOIN latest_job job
  ON job.entity_key = entity.entity_key
LEFT JOIN card_counts cards
  ON cards.entity_key = entity.entity_key;
`;
