import type { StocksBriefingModel } from '@/pages/research-workspace/model/stock-briefing';
import type { ResearchWorkspaceViewPayload } from '@/pages/research-workspace/model/workspace-view-payload';

type StocksPreviewPayload = Extract<ResearchWorkspaceViewPayload, { view: 'stocks' }>;

export const stocksPreviewFixture = {
  view: 'stocks',
  shell: {
    radarScopeTotal: 18,
    watchlistCount: 4,
  },
  stocks: {
    availability: 'available',
    data: [
      {
        entityKey: 'KR:005930',
        ticker: '005930',
        market: 'KR',
        name: '삼성전자',
        displayName: '삼성전자',
        isWatched: false,
        isHolding: true,
        latestPrice: 81200,
        currency: 'KRW',
        changePct: 1.24,
        primaryThesis: 'HBM 수요와 메모리 가격 흐름을 함께 복기합니다.',
        confidence: 'medium',
        analysisStatus: 'cached',
        lastAnalyzedAt: '2026-08-07T00:00:00.000Z',
      },
      {
        entityKey: 'KR:000660',
        ticker: '000660',
        market: 'KR',
        name: 'SK하이닉스',
        displayName: 'SK하이닉스',
        isWatched: false,
        isHolding: true,
        latestPrice: 284000,
        currency: 'KRW',
        changePct: 2.1,
        primaryThesis: 'HBM 공급 확대와 고객 다변화가 이어지는지 확인합니다.',
        confidence: 'medium',
        analysisStatus: 'cached',
        lastAnalyzedAt: '2026-08-06T08:30:00.000Z',
      },
      {
        entityKey: 'KR:035420',
        ticker: '035420',
        market: 'KR',
        name: 'NAVER',
        displayName: 'NAVER',
        isWatched: false,
        isHolding: true,
        latestPrice: 241500,
        currency: 'KRW',
        changePct: -0.42,
        primaryThesis: '광고 회복과 AI 서비스 비용 구조를 함께 확인합니다.',
        confidence: 'medium',
        analysisStatus: 'cached',
        lastAnalyzedAt: '2026-08-06T01:00:00.000Z',
      },
      {
        entityKey: 'KR:005380',
        ticker: '005380',
        market: 'KR',
        name: '현대자동차',
        displayName: '현대자동차',
        isWatched: false,
        isHolding: true,
        latestPrice: 298000,
        currency: 'KRW',
        changePct: 0.31,
        primaryThesis: '지역별 판매 구성과 관세 변화를 정기적으로 확인합니다.',
        confidence: 'medium',
        analysisStatus: 'cached',
        lastAnalyzedAt: '2026-08-04T03:00:00.000Z',
      },
      {
        entityKey: 'KR:051910',
        ticker: '051910',
        market: 'KR',
        name: 'LG화학',
        displayName: 'LG화학',
        isWatched: false,
        isHolding: true,
        latestPrice: 331000,
        currency: 'KRW',
        changePct: -0.85,
        primaryThesis: '석유화학 수익성과 배터리 소재 수요를 함께 복기합니다.',
        confidence: 'low',
        analysisStatus: 'stale',
        lastAnalyzedAt: '2026-08-02T09:00:00.000Z',
      },
      {
        entityKey: 'US:NVDA',
        ticker: 'NVDA',
        market: 'US',
        name: 'NVIDIA',
        displayName: 'NVIDIA',
        isWatched: true,
        isHolding: false,
        latestPrice: 176.42,
        currency: 'USD',
        changePct: -0.68,
        analysisStatus: 'stale',
        lastAnalyzedAt: '2026-08-05T10:30:00.000Z',
      },
      {
        entityKey: 'US:MU',
        ticker: 'MU',
        market: 'US',
        name: 'Micron Technology',
        displayName: 'Micron',
        isWatched: true,
        isHolding: false,
        latestPrice: 126.18,
        currency: 'USD',
        changePct: 1.08,
        analysisStatus: 'cached',
        lastAnalyzedAt: '2026-08-05T07:00:00.000Z',
      },
      {
        entityKey: 'US:MSFT',
        ticker: 'MSFT',
        market: 'US',
        name: 'Microsoft',
        displayName: 'Microsoft',
        isWatched: true,
        isHolding: false,
        latestPrice: 524.1,
        currency: 'USD',
        changePct: 0.16,
        analysisStatus: 'cached',
        lastAnalyzedAt: '2026-08-03T04:00:00.000Z',
      },
      {
        entityKey: 'US:TSM',
        ticker: 'TSM',
        market: 'US',
        name: 'Taiwan Semiconductor Manufacturing',
        displayName: 'TSMC',
        isWatched: true,
        isHolding: false,
        latestPrice: 242.75,
        currency: 'USD',
        changePct: 0.73,
        analysisStatus: 'cached',
        lastAnalyzedAt: '2026-08-01T02:00:00.000Z',
      },
    ],
    error: null,
    meta: {
      source: 'mock',
      generatedAt: '2026-08-07T00:00:00.000Z',
    },
  },
} satisfies StocksPreviewPayload;

export const stocksBriefingPreviewFixture = {
  summary: {
    holdingCount: 5,
    connectedNewsCount: 8,
    riskCount: 3,
    analyzedAt: '2026-08-07T00:00:00.000Z',
  },
  priorityHoldings: [
    {
      entityKey: 'KR:005930',
      priority: 1,
      changeSummary: 'HBM 공급망과 메모리 가격 관련 새 근거가 연결됐습니다.',
      connectionReason: '보유 종목과 직접 연결된 반도체 공급망 변화',
      newsCount: 3,
      primaryPath: 'AI 인프라 → HBM → 메모리 공급',
      riskSummary: '메모리 가격 변동성과 설비 투자 속도를 확인합니다.',
    },
    {
      entityKey: 'KR:000660',
      priority: 2,
      changeSummary: '고대역폭 메모리 고객 확대 관련 공시를 확인할 수 있습니다.',
      connectionReason: '보유 종목의 핵심 제품 수요와 연결된 변화',
      newsCount: 2,
      primaryPath: 'AI 가속기 → HBM 수요 → 메모리 생산',
      riskSummary: '공급 확대 속도와 고객 집중도를 함께 확인합니다.',
    },
    {
      entityKey: 'KR:035420',
      priority: 3,
      changeSummary: '광고와 AI 서비스 비용 구조를 복기할 새 자료가 있습니다.',
      connectionReason: '보유 논지의 광고 회복과 AI 투자비 점검',
      newsCount: 1,
      primaryPath: '온라인 광고 → 플랫폼 매출 → AI 서비스 투자',
      riskSummary: 'AI 투자 증가가 수익성에 미치는 범위를 확인합니다.',
    },
  ],
  watchlistChanges: [
    {
      entityKey: 'US:NVDA',
      changeSummary: 'AI 가속기 공급 일정 관련 새 소식이 연결됐습니다.',
      connectionReason: '관심 종목의 공급망 일정 변화',
      newsCount: 1,
      primaryPath: '데이터센터 투자 → AI 가속기 수요',
    },
    {
      entityKey: 'US:MU',
      changeSummary: '메모리 업황 관련 최근 자료를 확인할 수 있습니다.',
      connectionReason: '관심 종목과 메모리 가격 흐름의 연결',
      newsCount: 1,
      primaryPath: '메모리 가격 → 생산 조정 → 수익성',
    },
  ],
} satisfies StocksBriefingModel;
